[package]
name = "aoc2020"
version = "0.1.0"
authors = ["Nick Chow <nicky.chow@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.34"
env_logger = "0.8.2"
